---
 name: CI
 on: [push,pull_request]
 jobs:
   ct:
     name: Go Test
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v1
       - name: Set up Go
         uses: actions/setup-go@v1
         with:
           go-version: 1.14
         id: go
       - name: Run Test
         run: |
           make test
